// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASaXy1sydrK_IpUYzX2row-lDBaeRXJWk',
    appId: '1:247044733190:web:dece18939a87b4d71c0687',
    messagingSenderId: '247044733190',
    projectId: 'thbatchfirebase',
    authDomain: 'thbatchfirebase.firebaseapp.com',
    storageBucket: 'thbatchfirebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEZzmYkYb2Zx8bfKEc8bBX4iFBUNgohFI',
    appId: '1:247044733190:android:79890a2f9cc5c7bf1c0687',
    messagingSenderId: '247044733190',
    projectId: 'thbatchfirebase',
    storageBucket: 'thbatchfirebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJeC1zW61LItS_fg5IgY6QOWrqzmmM_Fk',
    appId: '1:247044733190:ios:e983bb468166e3b81c0687',
    messagingSenderId: '247044733190',
    projectId: 'thbatchfirebase',
    storageBucket: 'thbatchfirebase.firebasestorage.app',
    iosBundleId: 'com.example.firebaseClassSeventeenBatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJeC1zW61LItS_fg5IgY6QOWrqzmmM_Fk',
    appId: '1:247044733190:ios:e983bb468166e3b81c0687',
    messagingSenderId: '247044733190',
    projectId: 'thbatchfirebase',
    storageBucket: 'thbatchfirebase.firebasestorage.app',
    iosBundleId: 'com.example.firebaseClassSeventeenBatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASaXy1sydrK_IpUYzX2row-lDBaeRXJWk',
    appId: '1:247044733190:web:2dbc4e0ac70773c21c0687',
    messagingSenderId: '247044733190',
    projectId: 'thbatchfirebase',
    authDomain: 'thbatchfirebase.firebaseapp.com',
    storageBucket: 'thbatchfirebase.firebasestorage.app',
  );
}
